"""Adicionando a coluna de nome do usuario ao pedido

Revision ID: 5ba1ac31ab46
Revises: 670fef58b810
Create Date: 2026-01-12 22:16:45.273885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba1ac31ab46'
down_revision: Union[str, Sequence[str], None] = '670fef58b810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('nome_usuario', sa.String()))
    # ### end Alembic commands ###

    op.execute("""
            UPDATE orders
            SET nome_usuario = 'Sistema'
            WHERE nome_usuario IS NULL
        """)

    op.alter_column(
        "orders",
        "nome_usuario",
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'nome_usuario')
    # ### end Alembic commands ###
