"""versao 2

Revision ID: dd95123f2d48
Revises: 713c2e999c2e
Create Date: 2026-01-15 01:57:59.640837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd95123f2d48'
down_revision: Union[str, Sequence[str], None] = '713c2e999c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(), nullable=False),
    sa.Column('pedido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('users')
    # ### end Alembic commands ###
